add:基本コーディングStep1
gizumo-education/front-coding pull request #172
Opened 2024-12-02 06:18 UTC by kiyosakitaisei

## チケットのリンク
[GIZFE-2036](https://gizumo.backlog.com/view/GIZFE-2036) 基本コーディング

## やったこと
・keyvisualの表示、画像、文字をpositionで設置
・「お仕事検索」のformの設置
・sliserの画像、リスト、ボタンの設置
・FLOCSSでcssの管理
・Sassでcssを命名、指示を行なった

## 動作確認

以下の全ての項目にチェックがついていること  
（チェックは `- [x]` のように「x」をつけるか保存後にチェックボックスをクリック）

- [ x ] `develop_自分の名前`ブランチがPRのターゲットブランチになっていること
- [ x ] `npm run start` を実行した結果、エラーなく起動すること
- [ x ] [デザインチェック](https://gizumo.backlog.com/alias/wiki/3326589)を実施し、デザインとずれがないこと
- [ x ] [HTMLバリデータ](https://validator.w3.org/nu/)でエラーがないこと
- [ x ] [Files changed](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests)タブを確認し、不要な差分や実装漏れがないか確認できていること
- [ x ] 画面表示に問題がないことを確認し、画面キャプチャが以下に添付できていること

## 特にレビューをお願いしたい箇所
なし

![FireShot Capture 014 - 医療事務求人を探すならギズジョブ - localhost](https://github.com/user-attachments/assets/f04823be-26cc-48eb-acf6-67bcbebcb15c)

2024-12-03 02:11 UTC, keisuke3 requested changes

2024-12-03 02:11 UTC, keisuke3 commented on src/index.html
> +                  <li class="p-slider__box__slide__contents__block__list__inner"><span
[ask]
こちらのclass名がかなり長くなってますが、長くした意図ってありますか？？

2024-12-03 02:11 UTC, keisuke3 commented on src/css/object/project/slider.scss
> +  .arrow__r {
[imo]
`__r`のrはrightのrだと思うのですが、単語の省略は読む人によって解釈が変わってくるので、基本的に省略しないようにしましょう！

2024-12-03 03:46 UTC, kiyosakitaisei commented on src/index.html
> +                  <li class="p-slider__box__slide__contents__block__list__inner"><span
>こちらのclass名がかなり長くなってますが、長くした意図ってありますか？？

sassの「＆__〇〇」で記述できるようにこのように対応していたため、長すぎると扱いずらい、見ずらいと思いながらも長くなってしまっています。

2024-12-03 03:59 UTC, kiyosakitaisei commented on src/css/object/project/slider.scss
> +  .arrow__r {
承知しました！
対応いたしました。

2024-12-03 05:01 UTC, keisuke3 commented on src/index.html
> +                  <li class="p-slider__box__slide__contents__block__list__inner"><span
@kiyosakitaisei 
子要素のclass名に親要素のclass名をすべて付けないといけないわけではないので、修正してしまって大丈夫ですよ！
FLOCSSの命名規則は、命名が被らないことが目的なので、

2024-12-03 07:18 UTC, kiyosakitaisei commented on src/index.html
> +                  <li class="p-slider__box__slide__contents__block__list__inner"><span
ご教授ありがとうございました。
対応いたしました！

「p-slider__contents__block__list__inner__area」を
「p-slider__list__inner__area」にすることも試みたのですが「contents」「block」に対して余白、　widthを指定しており崩れてしまい戻しました。
ご確認お願いいたします。

2024-12-04 03:09 UTC, keisuke3 approved these changes

2024-12-04 03:10 UTC, merged