add:基本コーディングStep2
gizumo-education/front-coding pull request #173
Opened 2024-12-04 08:03 UTC by kiyosakitaisei

## チケットのリンク
[GIZFE-2036](https://gizumo.backlog.com/view/GIZFE-2036) 基本コーディング

## やったこと
・ギズジョブの4つの特徴の作成
・転職までの流れの作成
・転職お役立ちコンテンツの作成
・h2のスタイルの共通化
・formのmarginの共通化

## 動作確認

以下の全ての項目にチェックがついていること  
（チェックは `- [x]` のように「x」をつけるか保存後にチェックボックスをクリック）

- [ ] `develop_自分の名前`ブランチがPRのターゲットブランチになっていること
- [ ] `npm run start` を実行した結果、エラーなく起動すること
- [ ] [デザインチェック](https://gizumo.backlog.com/alias/wiki/3326589)を実施し、デザインとずれがないこと
- [ ] [HTMLバリデータ](https://validator.w3.org/nu/)でエラーがないこと
- [ ] [Files changed](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests)タブを確認し、不要な差分や実装漏れがないか確認できていること
- [ ] 画面表示に問題がないことを確認し、画面キャプチャが以下に添付できていること

## 特にレビューをお願いしたい箇所
なし

2024-12-04 08:55 UTC, keisuke3 requested changes

2024-12-04 08:55 UTC, keisuke3 commented on src/css/layout/footer.scss
> +    margin-top: 200px;
[must]
`margin-top`で間隔を取ってくれてると思うのですが、デザインよりも「お仕事検索」とフッターの距離が離れてしまっているので、間隔の調整をお願いします！

2024-12-04 08:55 UTC, keisuke3 commented on src/index.html
> +    <div class="p-useful">
[must]
ヘッダーよりも「転職お役立ちコンテンツ」エリアの方が上に表示されてしまっているので、修正をお願いします！

<img width="1440" alt="スクリーンショット 2024-12-04 17 42 09" src="https://github.com/user-attachments/assets/ca0d3322-6fe0-4b9f-9181-8069e7408ae4">

2024-12-04 08:55 UTC, keisuke3 commented on src/css/object/project/features.scss
> +      height: 180px;
[must]
要素には基本的に`height`は指定しないようにしましょう！
今回だと中身のコンテンツの高さが180pxよりも高くなってしまった時、スタイル崩れが起きてしまいます！

`height`を指定するのではなく、`padding-bottom`を使用して内側の余白を確保することで高さを担保しましょう！
CSSを書く時は`height`や`width` の指定がスタイル崩れの原因になることが多いので、指定しなくても問題なさそうな時はなるべく指定しないようにすると良いです！

2024-12-04 08:55 UTC, keisuke3 commented on src/css/object/project/useful.scss
> +      margin-top: 80px;
[must]
`margin`は要素と要素の間隔を確保するためのプロパティなので、一番外側のdivタグに使用しましょう！
今回だと`btn`classが良いと思います！

2024-12-05 02:48 UTC, kiyosakitaisei commented on src/css/layout/footer.scss
> +    margin-top: 200px;
「/src/css/object/utility/margin.scss」で
お仕事検索のformに対して「margin: 150px auto 200px;」を指定してしまっていたため距離が大きく開いてしまっていました。
「margin: 150px auto 0;」に修正いたしました。

2024-12-05 02:48 UTC, kiyosakitaisei commented on src/index.html
> +    <div class="p-useful">
/src/css/layout/header.scss
こちらのファイルに「z-index: 1000;」を追加していたので「z-index: 2000;」で対応いたしました。

2024-12-05 02:48 UTC, kiyosakitaisei commented on src/css/object/project/features.scss
> +      height: 180px;
承知いたしました！
「padding-bottom: 55px;」で対応いたしました。


「/src/css/object/project/features.scss」の
「height: 180px;」に記載も「padding-bottom: 40px;」に修正いたしました。

2024-12-05 02:48 UTC, kiyosakitaisei commented on src/css/object/project/useful.scss
> +      margin-top: 80px;
承知いたしました。
下記で対応いたしました。


&__btn {
    width: 420px;
      margin: 80px auto 0;

2024-12-05 06:04 UTC, keisuke3 approved these changes

2024-12-05 06:04 UTC, merged