add:基本コーディングStep3
gizumo-education/front-coding pull request #175
Opened 2024-12-09 07:44 UTC by kiyosakitaisei

## チケットのリンク
[GIZFE-2036](https://gizumo.backlog.com/view/GIZFE-2036) 基本コーディング

## やったこと
レスポンシブ対応

## 動作確認

以下の全ての項目にチェックがついていること  
（チェックは `- [x]` のように「x」をつけるか保存後にチェックボックスをクリック）

- [ ] `develop_自分の名前`ブランチがPRのターゲットブランチになっていること
- [ ] `npm run start` を実行した結果、エラーなく起動すること
- [ ] [デザインチェック](https://gizumo.backlog.com/alias/wiki/3326589)を実施し、デザインとずれがないこと
- [ ] [HTMLバリデータ](https://validator.w3.org/nu/)でエラーがないこと
- [ ] [Files changed](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests)タブを確認し、不要な差分や実装漏れがないか確認できていること
- [ ] 画面表示に問題がないことを確認し、画面キャプチャが以下に添付できていること

## 特にレビューをお願いしたい箇所
なし

2024-12-09 09:05 UTC, ryo-kihara commented
見た目のところから優先的に確認しました
SP は問題なさそうですが、TABとPCで横スクロールが発生してしまっていました。

- TAB
  - PC で設定した px に対して 1/100 した値を rem で設定するようにお願いします
- PC
  - どこかのスタイルか幅が原因で1262pxの幅が取られてしまっていて横スクロールできてしまう状況ということは確認したので、原因特定と修正お願いしたいです

https://github.com/user-attachments/assets/cdf52e38-fa7a-4794-a68e-54c494392436

ちなみに上記の画面収録は Responsive Viewer という拡張機能で確認したものです。
超便利なので入れてみてください
https://chromewebstore.google.com/detail/responsive-viewer/inmopeiepgfljkpkidclfgbgbmfcennb

2024-12-10 09:37 UTC, kiyosakitaisei commented
＞TAB
＞PC で設定した px に対して 1/100 した値を rem で設定するようにお願いします

tab表示の際remで設定し修正いたしました。


＞PC
＞どこかのスタイルか幅が原因で1262pxの幅が取られてしまっていて横スクロールできてしまう状況ということは確認したので、原因特定と修正お願いしたいです

キービジュアルの画像に1262pxがありました。
「width、margin:auto;」を削除し「background-image」に対し
    background-position: center;
    background-repeat: no-repeat;
で対応いたしました。

＞ちなみに上記の画面収録は Responsive Viewer という拡張機能で確認したものです。
＞超便利なので入れてみてください

ありがとうございます！
使いこなせるようにいたします！

2024-12-11 08:26 UTC, keisuke3 requested changes

2024-12-11 08:26 UTC, keisuke3 commented on src/index.html
> +        <h2 class="p-slider__title u-h2__sp">新着求人</h2>
[must]
コンテンツの最大幅をそれぞれのセクションで書いてくれていると思うのですが、ここはlayout.scssに定義した`l-inner`classを使ってあげた方が良さそうですね！
せっかく共通化してくれているので、共通化したclassを使用するようにしましょう！

2024-12-12 09:09 UTC, kiyosakitaisei commented on src/index.html
> +        <h2 class="p-slider__title u-h2__sp">新着求人</h2>
承知しました！
width: 1180px;を検索して共通化いたしました！

2024-12-13 07:58 UTC, keisuke3 requested changes

2024-12-13 07:58 UTC, keisuke3 commented on src/index.html
> +    <div class="p-slider l-inner">
[must]
innerを設定したことで`background-color`の表示領域が狭くなっているので、修正をお願いします！

<img width="1440" alt="スクリーンショット 2024-12-13 16 56 50" src="https://github.com/user-attachments/assets/cd6d6d1b-e6b1-41c0-926f-c042561d188c" />

2024-12-18 02:23 UTC, kiyosakitaisei commented on src/index.html
> +    <div class="p-slider l-inner">
失礼しました。

「l-inner」をつける箇所が間違っていたため修正しました。
また「margin-top」がなかったため追記の対応いたしました。

2025-07-01 04:13 UTC, closed without merging